const data = {
  products: [
    {
      _id: "1",
      name: "Razer Viper Ultimate",
      category: "Mouse",
      image: "/images/razer.jpg",
      price: 120.95,
      brand: "Razer",
      rating: 5,
      numReviews: 22,
      description:
        "In our humble opinion, this is the best gaming mouse on the market right now!",
    },
    {
      _id: "2",
      name: "Razer Mamba",
      category: "Mouse",
      image: "/images/razer.jpg",
      price: 80.95,
      brand: "Razer",
      rating: 4.5,
      numReviews: 13,
      description: "Not a bad mouse at all give it a try",
    },
    {
      _id: "3",
      name: "Logitech G903 LIGHTSPEED",
      category: "Mouse",
      image: "/images/logitech.jpg",
      price: 95.0,
      brand: "Logitech",
      rating: 4.5,
      numReviews: 10,
      description: "Not a bad mouse at all give it a try",
    },
    {
      _id: "4",
      name: "Logitech G PRO Wireless",
      category: "Mouse",
      image: "/images/logitech.png",
      price: 95.95,
      brand: "Logitech",
      rating: 4.5,
      numReviews: 17,
      description: "Not a bad mouse at all give it a try",
    },
    {
      _id: "5",
      name: "Logitech G915 LIGHTSPEED",
      category: "Keyboard",
      image: "/images/logi-keyboard.jpg",
      price: 195.99,
      brand: "Logitech",
      rating: 4.5,
      numReviews: 12,
      description: "Not a bad keyboard at all give it a try",
    },
    {
      _id: "6",
      name: "Razer BlackWidow Elite",
      category: "Keyboard",
      image: "/images/razer-keyboard.jpg",
      price: 124.89,
      brand: "Razer",
      rating: 4.5,
      numReviews: 14,
      description: "Not a bad keyboard at all give it a try",
    },
  ],
};
